version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html/reading_output

hooks:
  AfterInstall:
    - location: scripts_for_deploy/preparation.sh
      runas: root

permissions:
  - object: /home/ec2-user/scripts
    pattern: "**"
    owner: ec2-user
    group: nginx
    mode: 774
    type:
      - file